version: '3.7'
services:

  database:
    image: redis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: todo_db1
    ports:
      - "3306:3306"

  backend:
     image: nginx
     build:
      context: ./TodoApp  # Path to your React.js frontend Dockerfile
      dockerfile: Dockerfile
     ports:
      - "8080:8080"
     depends_on:
      - database
     environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
     networks:
      - my-network

  frontend:
     build:
      context: ./to-do-app  # Path to your React.js frontend Dockerfile
      dockerfile: Dockerfile
     ports:
      - "3000:3000"
     depends_on:
      - backend
     networks:
      - my-network

      
networks:
  my-network:
    driver: bridge